$Global:SoftwareList = @(
    # --- Internet ---
    [PSCustomObject]@{ Nome = "Brave Browser";      Id = "Brave.Brave";             Categoria = "Internet" },
    [PSCustomObject]@{ Nome = "Discord";            Id = "Discord.Discord";         Categoria = "Internet" },
    [PSCustomObject]@{ Nome = "Mozilla Firefox";    Id = "Mozilla.Firefox";         Categoria = "Internet" },
    [PSCustomObject]@{ Nome = "PicoTorrent";        Id = "PicoTorrent.PicoTorrent"; Categoria = "Internet" },
    [PSCustomObject]@{ Nome = "Thunderbird";        Id = "Mozilla.Thunderbird";     Categoria = "Internet" },
    [PSCustomObject]@{ Nome = "Unigram";            Id = "Unigram.Unigram";         Categoria = "Internet" },
    [PSCustomObject]@{ Nome = "Vencord";            Id = "Vendicated.Vencord";      Categoria = "Internet" },
    [PSCustomObject]@{ Nome = "WhatsApp";           Id = "WhatsApp.WhatsApp";       Categoria = "Internet" },
    [PSCustomObject]@{ Nome = "Zen Browser";        Id = "Zen-Team.Zen-Browser";    Categoria = "Internet" },

    # --- Multimídia ---
    [PSCustomObject]@{ Nome = "AIMP";               Id = "AIMP.AIMP";               Categoria = "Multimídia" },
    [PSCustomObject]@{ Nome = "Audacity";           Id = "Audacity.Audacity";       Categoria = "Multimídia" },
    [PSCustomObject]@{ Nome = "foobar2000";         Id = "PeterPawlowski.foobar2000"; Categoria = "Multimídia" },
    [PSCustomObject]@{ Nome = "HandBrake";          Id = "HandBrake.HandBrake";     Categoria = "Multimídia" },
    [PSCustomObject]@{ Nome = "K-Lite Codec Pack";  Id = "CodecGuide.K-LiteCodecPack.Full"; Categoria = "Multimídia" },
    [PSCustomObject]@{ Nome = "OBS Studio";         Id = "OBSProject.OBSStudio";    Categoria = "Multimídia" },
    [PSCustomObject]@{ Nome = "Spotify";            Id = "Spotify.Spotify";         Categoria = "Multimídia" },
    [PSCustomObject]@{ Nome = "Stremio";            Id = "Stremio.Stremio";         Categoria = "Multimídia" },
    [PSCustomObject]@{ Nome = "VLC";                Id = "VideoLAN.VLC";            Categoria = "Multimídia" },

    # --- Gráficos ---
    [PSCustomObject]@{ Nome = "Affinity";           Id = "Canva.Affinity";          Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "Blender";            Id = "BlenderFoundation.Blender"; Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "FastStone Viewer";   Id = "FastStone.Viewer";        Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "GIMP";               Id = "GIMP.GIMP";               Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "Greenshot";          Id = "Greenshot.Greenshot";     Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "Inkscape";           Id = "Inkscape.Inkscape";       Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "IrfanView";          Id = "IrfanSkiljan.IrfanView";  Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "Krita";              Id = "KDE.Krita";               Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "MediBang Paint";     Id = "MediBang.MediBangPaintPro"; Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "Paint.NET";          Id = "dotPDN.PaintDotNet";      Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "ShareX";             Id = "ShareX.ShareX";           Categoria = "Gráficos" },
    [PSCustomObject]@{ Nome = "XnView MP";          Id = "XnSoft.XnViewMP";         Categoria = "Gráficos" },

    # --- Jogos ---
    [PSCustomObject]@{ Nome = "Amazon Games";       Id = "Amazon.Games";            Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "EA App";             Id = "ElectronicArts.EADesktop"; Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "Epic Games";         Id = "EpicGames.EpicGamesLauncher"; Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "Fishstrap";          Id = "Fishstrap.Fishstrap";     Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "GOG Galaxy";         Id = "GOG.Galaxy";              Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "osu!lazer";          Id = "ppy.osu";                 Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "Prism Launcher";     Id = "PrismLauncher.PrismLauncher"; Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "Sonic Robo Blast 2"; Id = "SonicTeamJr.SonicRoboBlast2"; Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "Steam";              Id = "Valve.Steam";             Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "Ubisoft Connect";    Id = "Ubisoft.Connect";         Categoria = "Jogos" },
    [PSCustomObject]@{ Nome = "YARG";               Id = "YARC.YARCLauncher";       Categoria = "Jogos" },

    # --- Desenvolvimento ---
    [PSCustomObject]@{ Nome = ".NET 6";             Id = "Microsoft.DotNet.DesktopRuntime.6"; Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = ".NET 8";             Id = "Microsoft.DotNet.DesktopRuntime.8"; Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "FileZilla";          Id = "FileZilla.FileZilla";     Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "Git";                Id = "Git.Git";                 Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "Java 17";            Id = "EclipseAdoptium.Temurin.17.JDK"; Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "Java 21";            Id = "EclipseAdoptium.Temurin.21.JDK"; Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "Notepad++";          Id = "Notepad++.Notepad++";     Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "PuTTY";              Id = "PuTTY.PuTTY";             Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "Python 3";           Id = "Python.Python.3";         Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "Visual C++";         Id = "TechPowerUp.VCRedist";    Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "Visual Studio Code"; Id = "Microsoft.VisualStudioCode"; Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "WinMerge";           Id = "WinMerge.WinMerge";       Categoria = "Desenvolvimento" },
    [PSCustomObject]@{ Nome = "WinSCP";             Id = "WinSCP.WinSCP";           Categoria = "Desenvolvimento" },

    # --- Sistema ---
    [PSCustomObject]@{ Nome = "CPU-Z";              Id = "CPUID.CPU-Z";             Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "CrystalDiskInfo";    Id = "CrystalDewWorld.CrystalDiskInfo"; Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "Everything";         Id = "voidtools.Everything";    Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "GPU-Z";              Id = "TechPowerUp.GPU-Z";       Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "KeePassXC";          Id = "KeePassXCTeam.KeePassXC"; Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "LibreOffice";        Id = "TheDocumentFoundation.LibreOffice"; Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "Malwarebytes";       Id = "Malwarebytes.Malwarebytes"; Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "NanaZip";            Id = "M2Team.NanaZip";          Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "Notion";             Id = "Notion.Notion";           Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "Open-Shell";         Id = "Open-Shell.Open-Shell-Menu"; Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "PowerToys";          Id = "Microsoft.PowerToys";     Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "Radmin VPN";         Id = "Famatech.RadminVPN";      Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "Revo Uninstaller";   Id = "RevoUninstaller.RevoUninstaller"; Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "SumatraPDF";         Id = "SumatraPDF.SumatraPDF";   Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "TeraCopy";           Id = "CodeSector.TeraCopy";     Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "Virtual Desktop";    Id = "VirtualDesktop.Streamer"; Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "VRCX";               Id = "VRCX.VRCX";               Categoria = "Sistema" },
    [PSCustomObject]@{ Nome = "WizTree";            Id = "AntibodySoftware.WizTree"; Categoria = "Sistema" }
)
